#Peer Assignment 1
##1. Introduction
It is now possible to collect a large amount of data about personal movement using activity monitoring devices such as Fitbut, Nike Fuelband, or Jawbone Up. These type of devices are part of the "quantified self" movement - a group of enthusiasts who take measurements about themselves regularly to improve their health, to find patterns in their behavior, or because they are tech geeks. But these data remain under-utilized both because the raw data are hard to obtain and there is a lack of statistical methods and software for processing and interpreting the data.

##2. Codebook
This assignment makes use of data from a personal activity monitoring device. This device collects data at 5 minute intervals dthrough out the day. The data consists of two months of data from an anonymous individual collected during the months of October and November, 2012 and include the number of steps taken in 5 minute intervals each day. 

The following details are important to consider:

- The Dataset [link nog toevoegen]

The variables included in this dataset are:

- **steps**: Number of steps taken in a 5-minute interval (missing values are coded as `NA`)

- **date**: The date on which the measurement was taken in YYYY-MM-DD format

- **interval**: Identifier for the 5-minute interval in which measurement was taken

The dataset is stored in a comma-seperated-value (CSV) file and there are a total of 17,568 observations in the original dataset.

##3. Loading and preprocessing the data
1. Loading the data
```{r echo=TRUE}
data <- read.csv("./activity.csv")
```

2. Process/ transform data

##4. What is the mean total of steps taken per day?
*Note*: missing values are ignored in this step
1. Calculation of the total number of steps taken per day
2. Histogram of the total number of steps taken each day
3. Calculation and report mean and median of the total number of steps per day